/* Render the observatory from data/calibration.json — no frameworks, no
   hand-typed numbers. Generated by scripts/build_dashboard_data.py. */

(async function () {
  // --- live build strip ----------------------------------------------------
  // Reads the latest machine-appended build_events row (PolicyEngine populace
  // Supabase; RLS exposes read-only SELECT to this publishable key) while a
  // chain runs; hides itself when there is no fresh status.
  const LIVE_URL = "https://pgrhxxhiyqgngoffwden.supabase.co/rest/v1/runs";
  const LIVE_KEY = "sb_publishable_MmKzCHmEgOQNFlvj_RqZxQ_gPWRkrGh";
  async function pollLive() {
    try {
      const res = await fetch(
        `${LIVE_URL}?select=label,state,git_sha,started_at,` +
          `build_events(status,created_at)` +
          `&order=started_at.desc&limit=1` +
          `&build_events.order=created_at.desc&build_events.limit=1`,
        { headers: { apikey: LIVE_KEY, Authorization: `Bearer ${LIVE_KEY}` } }
      );
      if (!res.ok) return;
      const rows = await res.json();
      const run = rows?.[0];
      const st = run?.build_events?.[0]?.status;
      if (!st) return;
      // runs.state is the authoritative lifecycle (closed by the reporter,
      // swept if a chain crashes); the event supplies step-level detail.
      if (run.state) st.state = run.state;
      if (run.git_sha) st.run = `${st.run} @ ${run.git_sha}`;
      const box = document.getElementById("db-live");
      if (!box) return;
      const ageMin = (Date.now() - Date.parse(st.updated_at)) / 60000;
      const fresh = ageMin < 15 || st.state === "complete";
      if (!st.state || st.state === "starting" || !fresh) {
        box.style.display = "none";
        return;
      }
      box.style.display = "block";
      const stateEl = document.getElementById("db-live-state");
      stateEl.textContent = st.state.toUpperCase();
      stateEl.style.color =
        st.state === "complete" ? "var(--primary)" :
        st.state === "failed" ? "var(--destructive)" : "inherit";
      document.getElementById("db-live-step").textContent =
        `${st.run} — step ${st.chain_step}/5: ${st.step_name}`;
      const detail = [st.build_stage, st.last_line].filter(Boolean);
      document.getElementById("db-live-detail").textContent =
        detail[detail.length - 1] || "";
      const bits = [];
      if (st.calibration)
        bits.push(
          `calibration loss ${st.calibration.loss_from} -> ` +
          `${st.calibration.loss_to} | within10 ${st.calibration.within10_pct}%`
        );
      if (st.gates?.exported_nonzero)
        bits.push(
          `exported-nonzero ${st.gates.exported_nonzero.passed ? "PASS" : "FAIL"} ` +
          `(${st.gates.exported_nonzero.columns} cols)`
        );
      if (st.gates?.parity)
        bits.push(
          `parity ${st.gates.parity.passed ? "PASS" : "FAIL"} ` +
          `(${st.gates.parity.gaps} gaps)`
        );
      document.getElementById("db-live-gates").textContent = bits.join("  ·  ");
      document.getElementById("db-live-updated").textContent =
        `updated ${Math.max(0, Math.round(ageMin))} min ago — refreshes while a build runs`;
      if (st.state === "running") setTimeout(pollLive, 60000);
    } catch (e) {
      /* live strip is best-effort; the rest of the page is release data */
    }
  }
  pollLive();

  const want = new URLSearchParams(location.search).get("release");
  const url = want
    ? `./data/releases/${encodeURIComponent(want)}.json`
    : "./data/calibration.json";
  const res = await fetch(url, { cache: "no-store" });
  const d = await res.json();
  let releases = [];
  try {
    releases = await (await fetch("./data/releases/index.json", { cache: "no-store" })).json();
  } catch {}

  const $ = (id) => document.getElementById(id);
  const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
  };
  const pct = (x, digits = 1) => (100 * x).toFixed(digits) + "%";
  const compact = (x) => {
    const a = Math.abs(x);
    if (a >= 1e12) return (x / 1e12).toFixed(2) + "T";
    if (a >= 1e9) return (x / 1e9).toFixed(2) + "B";
    if (a >= 1e6) return (x / 1e6).toFixed(2) + "M";
    if (a >= 1e3) return (x / 1e3).toFixed(1) + "k";
    return String(Math.round(x));
  };

  $("db-stamp").textContent =
    "computed from build artifacts · regenerated " + d.generated_at;

  // --- stages -------------------------------------------------------------
  const stages = $("db-stages");
  for (const s of d.stages) {
    const card = el("div", "db-stage");
    const title = el("div", "db-stage-title");
    title.append(el("span", "db-dot " + s.status), el("span", null, s.title));
    const status = el("span", null, " — " + s.status);
    status.style.color = "var(--paper-faint)";
    title.append(status);
    card.append(title, el("div", "db-stage-note", s.note));
    stages.append(card);
  }

  // --- headline metrics ----------------------------------------------------
  const h = d.headline;
  const metric = (label, val, note) => {
    const m = el("div", "metric");
    m.append(el("span", "metric-label mono", label));
    const v = el("span", "metric-val", val);
    m.append(v, el("span", "metric-note", note));
    return m;
  };
  $("db-headline").append(
    metric(
      "targets within 10%",
      pct(h.within10_final),
      `of ${h.n_targets.toLocaleString()} administrative targets`
    ),
    metric(
      "calibration loss",
      `${h.loss_initial.toFixed(2)} → ${h.loss_final.toFixed(3)}`,
      "relative-error loss, before → after"
    ),
    metric(
      "represented population",
      `${compact(h.weighted_persons)}`,
      `from ${h.n_persons.toLocaleString()} person records in ` +
        `${h.n_households.toLocaleString()} synthetic households`
    )
  );

  // --- miss histogram -------------------------------------------------------
  const hist = $("db-hist");
  const maxCount = Math.max(...d.histogram.counts);
  d.histogram.labels.forEach((label, i) => {
    const count = d.histogram.counts[i];
    const row = el("div", "db-row");
    row.append(el("span", "db-row-label", "|miss| " + label));
    const bar = el("div", "db-bar");
    const fill = el("i", i >= 4 ? "dim" : null);
    fill.style.width = Math.max(0.6, (100 * count) / maxCount) + "%";
    bar.append(fill);
    row.append(bar);
    row.append(
      el("span", "db-row-val", `${count.toLocaleString()} targets`)
    );
    hist.append(row);
  });

  // --- families -------------------------------------------------------------
  const fams = $("db-families");
  for (const f of d.families.slice(0, 16)) {
    const row = el("div", "db-row");
    row.append(el("span", "db-row-label", f.family));
    const bar = el("div", "db-bar");
    const fill = el("i", f.within10 < 0.8 ? "dim" : null);
    fill.style.width = Math.max(0.6, 100 * f.within10) + "%";
    bar.append(fill);
    row.append(bar);
    row.append(
      el("span", "db-row-val", `${pct(f.within10, 0)} of ${f.n}`)
    );
    fams.append(row);
  }

  // --- worst targets ----------------------------------------------------------
  const worst = $("db-worst");
  const thead = el("tr");
  for (const t of ["target", "aimed", "achieved", "miss"])
    thead.append(el("th", null, t));
  worst.append(thead);
  for (const w of d.worst.slice(0, 10)) {
    const tr = el("tr");
    const name = el("td", null, w.name.replace(/^nation\//, ""));
    name.title = w.name;
    tr.append(name);
    const aimed = el("td", "num", compact(w.target));
    const achieved = el("td", "num", compact(w.estimate));
    const miss = el("td", "num hot", pct(w.abs_rel_err, 0));
    tr.append(aimed, achieved, miss);
    worst.append(tr);
  }

  // --- weights ------------------------------------------------------------------
  const wt = $("db-weights");
  const whead = el("tr");
  for (const t of [
    "weights",
    "total",
    "median",
    "p99",
    "max",
    "records > 500k",
  ])
    whead.append(el("th", null, t));
  wt.append(whead);
  const wrow = (label, s, hot) => {
    const tr = el("tr");
    tr.append(el("td", null, label));
    tr.append(el("td", "num", s.sum_M.toFixed(1) + "M"));
    tr.append(el("td", "num", s.p50.toLocaleString()));
    tr.append(el("td", "num", s.p99.toLocaleString()));
    tr.append(el("td", "num" + (hot ? " hot" : ""), s.max.toLocaleString()));
    tr.append(el("td", "num", s.n_gt_500k.toLocaleString()));
    return tr;
  };
  wt.append(wrow("design (input)", d.weights.design));
  if (d.weights.unbounded)
    wt.append(wrow("calibrated, unbounded", d.weights.unbounded, true));
  wt.append(
    wrow(`calibrated, shipped (${h.max_weight_ratio}× cap)`, d.weights.bounded)
  );

  // --- sources diagram -------------------------------------------------------
  (() => {
    const counts = {};
    for (const r of d.lineage || [])
      counts[r.source] = (counts[r.source] || 0) + 1;
    const SOURCES = [
      { name: "Census CPS ASEC 2023", note: "household structure · demographics · incomes · benefits · tenure · hours · occupation · retirement contributions · childcare", keys: ["cps-carried", "cps-derived"], cls: "primary" },
      { name: "IRS SOI Public Use File 2015 (uprated)", note: "tax detail: capital gains · dividends · interest · deduction inputs · pass-through · estates", keys: ["puf-imputed"], cls: "primary" },
      { name: "Census block crosswalk", note: "geography: state · county · tract · block · congressional district", keys: [], cls: "primary" },
      { name: "Fed SCF 2022", note: "wealth: accounts · stocks · bonds · debts · net worth · mortgage balance hints", keys: ["scf-imputed"], cls: "primary" },
      { name: "Census SIPP", note: "tip income for tipped occupations · household vehicles (count + value)", keys: ["sipp-imputed"], cls: "primary" },
      { name: "CPS-ORG", note: "hourly wage · paid-hourly status · union coverage", keys: ["org-imputed"], cls: "primary" },
      { name: "MEPS-IC parameters", note: "employer-sponsored insurance premiums", keys: ["meps-imputed"], cls: "primary" },
      { name: "Census ACS 2022", note: "rent for renter households", keys: ["acs-imputed"], cls: "primary" },
      { name: "Spec + microunit structure", note: "tax units · SPM units · families · marital units · clone strata", keys: ["spec/structural"], cls: "primary" },
    ];
    const TARGETS = { name: "IRS SOI · Census · program administrative totals", note: (d.headline.n_targets || 3704).toLocaleString() + " calibration targets (weights only — never values)" };
    const W = 980, ROW = 86, H = SOURCES.length * ROW + 40;
    const sx = 10, sw = 380, mx = 520, mw = 200, tx = 790, tw = 180;
    const midY = H / 2 - 20;
    let p = [];
    p.push(`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;font-family:var(--mono);">`);
    SOURCES.forEach((srcDef, i) => {
      const y = 16 + i * ROW;
      const n = srcDef.keys.reduce((a, k) => a + (counts[k] || 0), 0);
      const stroke = srcDef.cls === "transitional" ? "var(--amber)" : "var(--line)";
      const dash = srcDef.cls === "transitional" ? ' stroke-dasharray="5,4"' : "";
      p.push(`<rect x="${sx}" y="${y}" width="${sw}" height="${ROW - 18}" rx="6" fill="var(--ink-2)" stroke="${stroke}"${dash}/>`);
      p.push(`<text x="${sx + 14}" y="${y + 22}" fill="var(--paper)" font-size="13">${srcDef.name}${n ? ` · ${n} vars` : ""}</text>`);
      const words = srcDef.note.split(" ");
      let line = "", lines = [];
      for (const w2 of words) { if ((line + w2).length > 58) { lines.push(line); line = ""; } line += w2 + " "; }
      lines.push(line);
      lines.slice(0, 3).forEach((ln, k) =>
        p.push(`<text x="${sx + 14}" y="${y + 38 + k * 13}" fill="var(--paper-faint)" font-size="10.5">${ln.trim()}</text>`));
      p.push(`<path d="M ${sx + sw} ${y + (ROW - 18) / 2} C ${sx + sw + 60} ${y + (ROW - 18) / 2}, ${mx - 60} ${midY}, ${mx} ${midY}" fill="none" stroke="${srcDef.cls === "transitional" ? "var(--amber-soft)" : "var(--paper-faint)"}" stroke-opacity="0.55"${dash}/>`);
    });
    p.push(`<rect x="${mx}" y="${midY - 34}" width="${mw}" height="68" rx="6" fill="var(--ink-2)" stroke="var(--amber-soft)"/>`);
    p.push(`<text x="${mx + mw / 2}" y="${midY - 8}" text-anchor="middle" fill="var(--paper)" font-size="13">populace-us 2024</text>`);
    p.push(`<text x="${mx + mw / 2}" y="${midY + 10}" text-anchor="middle" fill="var(--paper-faint)" font-size="10.5">${(d.headline.n_households || 0).toLocaleString()} households</text>`);
    p.push(`<text x="${mx + mw / 2}" y="${midY + 24}" text-anchor="middle" fill="var(--paper-faint)" font-size="10.5">${compact(d.headline.weighted_persons)} people represented</text>`);
    p.push(`<path d="M ${mx + mw} ${midY} L ${tx} ${midY}" stroke="var(--paper-faint)" stroke-opacity="0.55"/>`);
    p.push(`<rect x="${tx}" y="${midY - 34}" width="${tw}" height="68" rx="6" fill="var(--ink-2)" stroke="var(--line)"/>`);
    p.push(`<text x="${tx + tw / 2}" y="${midY - 8}" text-anchor="middle" fill="var(--paper)" font-size="12">calibration</text>`);
    const tWords = TARGETS.name.split(" · ");
    tWords.forEach((tword, k) =>
      p.push(`<text x="${tx + tw / 2}" y="${midY + 8 + k * 12}" text-anchor="middle" fill="var(--paper-faint)" font-size="9.5">${tword}</text>`));
    p.push("</svg>");
    document.getElementById("db-sources-diagram").innerHTML = p.join("");
    document.getElementById("db-sources-note").textContent =
      "Variable counts are live from this release's lineage table. The dashed " +
      "Every donor is a primary survey; the enhanced CPS appears only as " +
      "the benchmark the finished dataset is scored against, never as a " +
      "build input. Calibration targets adjust weights only; no target " +
      "value is ever written into a record.";
  })();

  // --- lineage -------------------------------------------------------------
  const rel = document.getElementById("db-release");
  rel.textContent = "release " + (d.release || "—") + " · " + d.generated_at + "  ";
  for (const r of releases) {
    const a = el("a", "mono", r);
    a.href = "?release=" + encodeURIComponent(r) + "#lineage";
    a.style.cssText =
      "margin-left:10px;padding:2px 8px;border:1px solid var(--line);" +
      "border-radius:3px;text-decoration:none;color:" +
      (r === d.release ? "var(--amber-soft)" : "var(--paper-faint)");
    rel.append(a);
  }
  const lin = d.lineage || [];
  const ltable = $("db-lineage");
  const lnote = $("db-lineage-note");
  const renderLineage = (q) => {
    ltable.replaceChildren();
    const head = el("tr");
    for (const t of ["variable", "source", "fill", "total", "eCPS fill", "eCPS total", "status"])
      head.append(el("th", null, t));
    ltable.append(head);
    const ql = (q || "").toLowerCase();
    const rows = lin.filter((r) => !ql || r.variable.includes(ql) || (r.source || "").includes(ql));
    for (const r of rows.slice(0, 60)) {
      const tr = el("tr");
      tr.append(el("td", null, r.variable));
      tr.append(el("td", null, r.source || "—"));
      tr.append(el("td", "num", r.fill == null ? "—" : pct(r.fill, 1)));
      tr.append(el("td", "num", r.total_B == null ? "—" : compact(r.total_B * 1e9)));
      tr.append(el("td", "num", r.ecps_fill == null ? "—" : pct(r.ecps_fill, 1)));
      tr.append(el("td", "num", r.ecps_total_B == null ? "—" : compact(r.ecps_total_B * 1e9)));
      tr.append(el("td", r.status === "gap" ? "hot" : null, r.status));
      ltable.append(tr);
    }
    const gaps = lin.filter((r) => r.status === "gap").length;
    lnote.textContent =
      `${rows.length} of ${lin.length} variables shown` +
      (rows.length > 60 ? " (first 60; refine the filter)" : "") +
      ` · ${gaps} gaps remain vs the incumbent in this release.`;
  };
  renderLineage("");
  document
    .getElementById("db-lineage-search")
    .addEventListener("input", (e) => renderLineage(e.target.value));

  // --- score ---------------------------------------------------------------------
  const text = $("db-score-text");
  const sm = $("db-score-metrics");
  if (d.score.status === "complete" && d.score.candidate) {
    const pt = d.score.per_target || {};
    text.textContent =
      "The shipped artifact, scored by the matched-sample, symmetric-refit " +
      `comparison against the enhanced CPS (${(
        d.score.matched_households || 0
      ).toLocaleString()} matched households). Lower is better. The aggregate ` +
      "wins are large; per individual target the incumbent still wins " +
      `${(pt.baseline_wins || 0).toLocaleString()} of ${(
        pt.n_targets || 0
      ).toLocaleString()} to our ${(pt.candidate_wins || 0).toLocaleString()} — ` +
      "we win big where we win and lose narrowly where we lose. Both facts " +
      "are the story.";
    for (const [label, key, note] of [
      ["training loss", "train_loss", "calibration targets"],
      ["held-out loss", "holdout_loss", `${pt.holdout_targets || ""} unseen targets`],
      ["full-surface loss", "full_loss", "all targets"],
    ]) {
      const m = el("div", "metric");
      m.append(el("span", "metric-label mono", label));
      const v = el("span", "metric-val", d.score.candidate[key].toFixed(3));
      v.append(
        el("span", "metric-vs", "vs " + d.score.baseline[key].toFixed(3))
      );
      m.append(v, el("span", "metric-note", note));
      sm.append(m);
    }
  } else {
    text.textContent =
      "The matched-sample, symmetric-refit comparison of the published " +
      "artifact against the enhanced CPS is running now; this section fills " +
      "in from the result file when it lands. The pool it ships from already " +
      "beat the incumbent in the first end-to-end benchmark — see the " +
      "evidence section on the front page.";
  }
})();
