/* Render the observatory from data/calibration.json — no frameworks, no
   hand-typed numbers. Generated by scripts/build_dashboard_data.py. */

(async function () {
  const res = await fetch("./data/calibration.json", { cache: "no-store" });
  const d = await res.json();

  const $ = (id) => document.getElementById(id);
  const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
  };
  const pct = (x, digits = 1) => (100 * x).toFixed(digits) + "%";
  const compact = (x) => {
    const a = Math.abs(x);
    if (a >= 1e12) return (x / 1e12).toFixed(2) + "T";
    if (a >= 1e9) return (x / 1e9).toFixed(2) + "B";
    if (a >= 1e6) return (x / 1e6).toFixed(2) + "M";
    if (a >= 1e3) return (x / 1e3).toFixed(1) + "k";
    return String(Math.round(x));
  };

  $("db-stamp").textContent =
    "computed from build artifacts · regenerated " + d.generated_at;

  // --- stages -------------------------------------------------------------
  const stages = $("db-stages");
  for (const s of d.stages) {
    const card = el("div", "db-stage");
    const title = el("div", "db-stage-title");
    title.append(el("span", "db-dot " + s.status), el("span", null, s.title));
    const status = el("span", null, " — " + s.status);
    status.style.color = "var(--paper-faint)";
    title.append(status);
    card.append(title, el("div", "db-stage-note", s.note));
    stages.append(card);
  }

  // --- headline metrics ----------------------------------------------------
  const h = d.headline;
  const metric = (label, val, note) => {
    const m = el("div", "metric");
    m.append(el("span", "metric-label mono", label));
    const v = el("span", "metric-val", val);
    m.append(v, el("span", "metric-note", note));
    return m;
  };
  $("db-headline").append(
    metric(
      "targets within 10%",
      pct(h.within10_final),
      `of ${h.n_targets.toLocaleString()} administrative targets`
    ),
    metric(
      "calibration loss",
      `${h.loss_initial.toFixed(2)} → ${h.loss_final.toFixed(3)}`,
      "relative-error loss, before → after"
    ),
    metric(
      "represented population",
      `${compact(h.weighted_persons)}`,
      `from ${h.n_persons.toLocaleString()} person records in ` +
        `${h.n_households.toLocaleString()} synthetic households`
    )
  );

  // --- miss histogram -------------------------------------------------------
  const hist = $("db-hist");
  const maxCount = Math.max(...d.histogram.counts);
  d.histogram.labels.forEach((label, i) => {
    const count = d.histogram.counts[i];
    const row = el("div", "db-row");
    row.append(el("span", "db-row-label", "|miss| " + label));
    const bar = el("div", "db-bar");
    const fill = el("i", i >= 4 ? "dim" : null);
    fill.style.width = Math.max(0.6, (100 * count) / maxCount) + "%";
    bar.append(fill);
    row.append(bar);
    row.append(
      el("span", "db-row-val", `${count.toLocaleString()} targets`)
    );
    hist.append(row);
  });

  // --- families -------------------------------------------------------------
  const fams = $("db-families");
  for (const f of d.families.slice(0, 16)) {
    const row = el("div", "db-row");
    row.append(el("span", "db-row-label", f.family));
    const bar = el("div", "db-bar");
    const fill = el("i", f.within10 < 0.8 ? "dim" : null);
    fill.style.width = Math.max(0.6, 100 * f.within10) + "%";
    bar.append(fill);
    row.append(bar);
    row.append(
      el("span", "db-row-val", `${pct(f.within10, 0)} of ${f.n}`)
    );
    fams.append(row);
  }

  // --- worst targets ----------------------------------------------------------
  const worst = $("db-worst");
  const thead = el("tr");
  for (const t of ["target", "aimed", "achieved", "miss"])
    thead.append(el("th", null, t));
  worst.append(thead);
  for (const w of d.worst.slice(0, 10)) {
    const tr = el("tr");
    const name = el("td", null, w.name.replace(/^nation\//, ""));
    name.title = w.name;
    tr.append(name);
    const aimed = el("td", "num", compact(w.target));
    const achieved = el("td", "num", compact(w.estimate));
    const miss = el("td", "num hot", pct(w.abs_rel_err, 0));
    tr.append(aimed, achieved, miss);
    worst.append(tr);
  }

  // --- weights ------------------------------------------------------------------
  const wt = $("db-weights");
  const whead = el("tr");
  for (const t of [
    "weights",
    "total",
    "median",
    "p99",
    "max",
    "records > 500k",
  ])
    whead.append(el("th", null, t));
  wt.append(whead);
  const wrow = (label, s, hot) => {
    const tr = el("tr");
    tr.append(el("td", null, label));
    tr.append(el("td", "num", s.sum_M.toFixed(1) + "M"));
    tr.append(el("td", "num", s.p50.toLocaleString()));
    tr.append(el("td", "num", s.p99.toLocaleString()));
    tr.append(el("td", "num" + (hot ? " hot" : ""), s.max.toLocaleString()));
    tr.append(el("td", "num", s.n_gt_500k.toLocaleString()));
    return tr;
  };
  wt.append(wrow("design (input)", d.weights.design));
  wt.append(wrow("calibrated, unbounded", d.weights.unbounded, true));
  wt.append(
    wrow(`calibrated, shipped (${h.max_weight_ratio}× cap)`, d.weights.bounded)
  );

  // --- score ---------------------------------------------------------------------
  const text = $("db-score-text");
  const sm = $("db-score-metrics");
  if (d.score.status === "complete" && d.score.raw) {
    const r = d.score.raw;
    text.textContent =
      "The published artifact, scored by the matched-sample, symmetric-refit " +
      "comparison against the enhanced CPS on the full target surface and " +
      "held-out targets.";
    const rows = [];
    const grab = (obj, keys) =>
      keys.reduce((o, k) => (o == null ? undefined : o[k]), obj);
    // Render whatever headline pairs the result JSON carries.
    const candidates = [
      ["full loss", ["candidate", "full_loss"], ["baseline", "full_loss"]],
      ["held-out loss", ["candidate", "holdout_loss"], ["baseline", "holdout_loss"]],
      ["mean sq. rel. error", ["candidate", "msre"], ["baseline", "msre"]],
    ];
    for (const [label, ck, bk] of candidates) {
      const c = grab(r, ck);
      const b = grab(r, bk);
      if (typeof c === "number" && typeof b === "number")
        rows.push([label, c, b]);
    }
    for (const [label, c, b] of rows) {
      const m = el("div", "metric");
      m.append(el("span", "metric-label mono", label));
      const v = el("span", "metric-val", c.toFixed(2));
      v.append(el("span", "metric-vs", "vs " + b.toFixed(2)));
      m.append(v, el("span", "metric-note", "populace vs enhanced CPS"));
      sm.append(m);
    }
    if (!rows.length) {
      text.textContent +=
        " (Result file present; see the evidence section for the scored numbers.)";
    }
  } else {
    text.textContent =
      "The matched-sample, symmetric-refit comparison of the published " +
      "artifact against the enhanced CPS is running now; this section fills " +
      "in from the result file when it lands. The pool it ships from already " +
      "beat the incumbent in the first end-to-end benchmark — see the " +
      "evidence section on the front page.";
  }
})();
